DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS relationship CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS reviews_likes CASCADE;
DROP TABLE IF EXISTS feed CASCADE;
DROP TABLE IF EXISTS directors CASCADE;
DROP TABLE IF EXISTS film_director CASCADE;

create table IF NOT EXISTS users
(
    user_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR NOT NULL,
    login    VARCHAR NOT NULL,
    name     VARCHAR,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS relationship
(
	user_id int NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
	friend_id int NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
	CONSTRAINT pk_friends PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS mpa
(
	mpa_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	mpa_name varchar NOT NULL
);

create table IF NOT EXISTS films
(
	film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar NOT NULL,
	description varchar(200),
	release_date DATE,
	duration int CHECK (duration > 0),
	mpa_id int REFERENCES mpa(mpa_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS likes
(
	film_id int REFERENCES films(film_id) ON DELETE CASCADE,
	user_id int REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genre
(
	genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	genre_name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genre
(
	film_id int REFERENCES films(film_id) ON DELETE CASCADE,
	genre_id int REFERENCES genre(genre_id) ON DELETE CASCADE
);

CREATE TABLE If NOT EXISTS reviews
(
    review_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content varchar,
    is_positive boolean,
    user_id int REFERENCES users(user_id) ON DELETE CASCADE,
    film_id int REFERENCES films(film_id) ON DELETE CASCADE
);

CREATE TABLE If NOT EXISTS reviews_likes
(
    review_id int REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id int REFERENCES users(user_id) ON DELETE CASCADE,
    is_positive boolean,
    PRIMARY KEY (review_id, user_id)
);

CREATE TABLE IF NOT EXISTS directors
(
    DIRECTOR_ID   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film_director
(
    film_id     int REFERENCES films (film_id) ON DELETE CASCADE,
    DIRECTOR_ID int REFERENCES DIRECTORS (DIRECTOR_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feed
(
    event_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES users(user_id) ON DELETE CASCADE,
    timestamp long not null,
    event_type varchar not null,
    operation varchar not null,
    entity_id int not null
);